### ISSUE TITLE
Watching changes in Markdown files

### ISSUE THREAD

**Issue by getDanArias** [EmilTholin/react-static-markdown-example#1]
Great work! This example has helped me understand how to integrate Markdown with the build workflow of `react-static`. Thanks :)

One area where I am struggling is that I'd like the browser to refresh when there are changes to the Markdown files. I've combined your approach with this other one:

https://github.com/pkrawc/react-static-markdown/blob/master/static.config.js

I plan to store the post in markdown under a folder. I changed the approach above to reading the posts folder inside the `/blog` route path. When I make changes to it, there is no rebuilding, which is great, but I have to manually refresh the browser to see the updated content reflected after a markdown change.

I'd appreciate any insight or guidance on how to achieve this please. It's the only thing I am missing to fully embrace this framework for a blog! 

Thank you for your time!

**Comment by EmilTholin** [comment]
Hi @getDanArias! Thank you for your kind words!

I'm not entirely sure how I would make the dev server refresh when changing markdown files, but `react-static` allows for [configuring the dev server options](https://react-static.js.org/api/#devserver). Maybe that could be used to get the desired effect?

Sounds like a good issue for `react-static`, more generally how to customize the watch behavior.

**Comment by getDanArias** [comment]
Thank you for your reply @EmilTholin ! I will create an issue there now :)
